# Generated by Django 5.1.3 on 2024-11-24 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="register",
            name="username",
            field=models.CharField(max_length=80, unique=True),
        ),
    ]
