# Generated by Django 5.1.3 on 2024-11-30 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profileAuth", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="register",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="register",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="register",
            name="is_superuser",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="register",
            name="last_login",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="last login"
            ),
        ),
    ]
