# Generated by Django 5.1.3 on 2024-11-30 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profileAuth", "0003_rename_is_staff_register_is_admin_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="register",
            name="password",
            field=models.CharField(max_length=128, verbose_name="password"),
        ),
    ]
