# Generated by Django 5.1.3 on 2024-12-03 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profile", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="lastName",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="nickName",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
